// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuemsslmcdmyzeoakprl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZW1zc2xtY2RteXplb2FrcHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTA4NjEsImV4cCI6MjA2NDM2Njg2MX0.scCIDO9JQIXpTqQM0IYh47YaQrk3yNs2jkGxoZJTo6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);